# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingAssignment' do
 
  pod 'Masonry'
  pod 'SDWebImage', '~> 4.0'
 
 target 'CodingAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
